<?php

/**
 * Implements hook_menu().
 */
function site_address_menu() {
  $items['admin/config/site_address'] = array(
    'title' => 'Site Address', 
    'page callback' => 'drupal_get_form',
    'page arguments' => array('site_address_form'),
    'access arguments' => array('access content')
  );
  return $items;
}

function site_address_form() {
  $form = array();

  $form['site_address_street'] = array(
    '#type' => 'textfield', 
    '#title' => t('Street'), 
    '#default_value' => variable_get('site_address_street', ''),
    '#required' => TRUE,
  );
  $form['site_address_city'] = array(
    '#type' => 'textfield', 
    '#title' => t('City'), 
    '#required' => TRUE,
  );
  /**
  * The State field
  */
  $form['site_address_state'] = array(
    '#type' => 'textfield', 
    '#title' => t('State'), 
    '#required' => TRUE,
  );

  $form['site_address_zip'] = array(
    '#type' => 'textfield', 
    '#title' => t('Zip Code'), 
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

function site_address_block_info() {
  $blocks = array();

  $blocks['site_address'] = array(
    'info' => t('Site Address')
  );
  return $blocks;
}