<?php

/**
 * Implements hook_menu().
 */
function site_address_menu() {
  $items['admin/config/site_address'] = array(
    'title' => 'Site Address', 
    'page callback' => 'drupal_get_form',
    'page arguments' => array('site_address_form'),
    'access arguments' => array('edit site address')
  );
  return $items;
}

/**
* Permissions
*/
function site_address_permission() {
  return array(
    'edit site address' => array(
      'title' => t('Edit Site Address'), 
      'description' => t('Allows to edit the site address.'),
    ),
  );
}


function site_address_form() {
  $form = array();

  $form['site_address_street'] = array(
    '#type' => 'textfield', 
    '#title' => t('Street'), 
    '#default_value' => variable_get('site_address_street', ''),
    '#required' => TRUE,
  );
  $form['site_address_city'] = array(
    '#type' => 'textfield', 
    '#title' => t('City'), 
    '#default_value' => variable_get('site_address_city', ''),
    '#required' => TRUE,
  );
  /**
  * The State field
  */
  $form['site_address_state'] = array(
    '#type' => 'textfield', 
    '#title' => t('State'), 
    '#default_value' => variable_get('site_address_state', ''),
    '#required' => TRUE,
  );

  $form['site_address_zip'] = array(
    '#type' => 'textfield', 
    '#title' => t('Zip Code'), 
    '#default_value' => variable_get('site_address_zip', ''),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

function site_address_block_info() {
  $blocks = array();

  $blocks['site_address'] = array(
    'info' => t('Site Address')
  );
  return $blocks;
}

function site_address_block_view($delta = '') {
  $block = array();
  switch( $delta ) {
    case 'site_address':
      $block['subject'] = t('Site Address');
      $site_address = variable_get('site_address_street'). "<br/>".  variable_get('site_address_city'). " ".  variable_get('site_address_state'). " ".  variable_get('site_address_zip');

      $block['content'] = '<address>'. $site_address. '</address>';
      break;
  }
  return $block;
}