<?php

/**
 * Implements hook_menu().
 */
function site_address_menu() {
  $items['admin/config/site_address'] = array(
    'title' => 'Site Address', 
    'page callback' => 'drupal_get_form',
    'page arguments' => array('site_address_form'),
    'access arguments' => array('access content')
  );
  return $items;
}

function site_address_form() {
  $form = array();

  $form['street'] = array(
    '#type' => 'textfield', 
    '#title' => t('Street'), 
    '#required' => TRUE,
  );
  $form['city'] = array(
    '#type' => 'textfield', 
    '#title' => t('City'), 
    '#required' => TRUE,
  );
  /**
  * The State field
  */
  $form['state'] = array(
    '#type' => 'textfield', 
    '#title' => t('State'), 
    '#required' => TRUE,
  );
  $form['zip'] = array(
    '#type' => 'textfield', 
    '#title' => t('Zip Code'), 
    '#required' => TRUE,
  );
  return $form;
}
